# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e899f8878e7095fe29fb65d503421b2f250e9936e90585b79347ef17e9ff5224b602fcd623a3936761c8384b4125c18a87601df44bfa66e9c860a38d4947db37

test:
  secret_key_base: 5ba7c1cde8000e6f70809b1db5ad823970e0ff9aeeb1703872bc01e8726d0a8b17e2c6cd79ba2e87fc9402f2217ff400fb84cd533b5030138062fc0c6c7cae0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
