# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b10f4aa4fd6a00359c512a0844e0f5bd7a22511c3e224bf216cca171d87ca0329619b7c633612e9d7e5e334aa34317d63100cec79f25048aab0d6e5370de7f2

test:
  secret_key_base: 94102bac6693a1d489cd906018820f7dab353baa0f4affef01cd247a6c2d2002fcd74938cd260998a45b7a270423fe1752378375f8404f45c1901777af7d232d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
