# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddfaf17361437d960a5b6b31d750528eca6e9f886408dc8bd38c2ae22b1eecc1a042180cc9711189f710fe2196c4ed776e9daf1df0303ab0671875cdd97e25be

test:
  secret_key_base: 14a7602dfcf1c3926858999784ed3c261665f04f49b3fd91da6607cea1feb29536ee8eaf8538db59147275788bce72c7fbd642fca5b2e8a15afe565f990671d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
